### ISSUE TITLE
Footer sitemap link incorrectly redirecting to Homepage

### ISSUE THREAD

**Issue by ccamel** [okp4/okp4-web#200]
## Issue

The sitemap link, which is located in the website's footer, is currently redirecting users back to the homepage rather than to the sitemap page.

<img width="403" alt="image" src="https://github.com/okp4/okp4-web/assets/9574336/1cefef35-be53-4c18-8754-f06c2d73966c">

## Steps to reproduce

Easy peazy. Navigate to the website's footer, then click on the 'Sitemap' link and observe that the browser redirects to the website's homepage.

## Suggested solutions

Since the sitemap page does not exist, I'd propose to remove the sitemap link from the footer to avoid user confusion.

**Comment by JulienMassonnat** [comment]
I removed it on this PR : https://github.com/okp4/okp4-web/pull/205
